# $HOME/Brewfile - jeff@jrhorn.me
#
# A manifest for homebrew packages
#

update

install vim --with-lua
install macvim
link --overwrite macvim
install git
install git-extras
install git-sh
install git-flow
install mercurial
install subversion
install the_silver_searcher
install chruby
install node
install ruby-install
install postgresql
install mysql
install ansible
install curl
install wget
install peg-markdown
install multimarkdown
install gnu-tar
install gnu-sed
install coreutils
install gnupg
install gnutls
install gpg-agent
link --overwrite gpg-agent
# apache
install httpd
install nmap
install sqlite
install tofrodos
install tree
install vagrant-completion
install wemux
# maybe down to 1.8?
install tmux
# switch tmux 1.8
# pin tmux
install reattach-to-user-namespace
install zsh
install direnv
install fasd
install ctags

tap phinze/cask
install brew-cask
# cask install google-chrome
linkapps
