# $HOME/Brewfile - jeff@jrhorn.me
#
# A manifest for homebrew packages
#

update

install vim
install macvim
install git
install git-extras
install mercurial
install subversion
install the_silver_searcher
install chruby
install node
install ruby-install
install postgresql
install mysql
install ansible
install curl
install wget
install peg-markdown
install multimarkdown
install gnu-tar
install gnu-sed
install coreutils
install gnupg
install gnutls
install gpg-agent
install httpd # apache
install nmap
install sqlite
install tofrodos
install tree
install vagrant-completion
install wemux
install tmux # maybe down to 1.8?
install zsh

tap phinze/cask
install brew-cask
# cask install google-chrome
