#!/bin/bash

action=$1
shift


[ "$action" = "usage" ] && {
  echo "  Add with the tags of most recent addition:"
  curcmd=`basename $0`
  echo "    $curcmd \"THING I NEED TO DO +project @context\""
  echo "      Append the tags of the most recently added item"
  echo "      to this item."
  echo ""
  exit
}

# get the last line added and extract context
line=`sed -n '$ =' "$TODO_FILE"`
# line="$(($line-1))" # subtract 1??
REGEX='[@|+][A-Za-z0-9]*'


echo "Appending:" $(sed $line"q;d" "$TODO_FILE" | grep -o "$REGEX")

"$TODO_FULL_SH" command add "$1"
newest=`sed -n '$ =' "$TODO_FILE"`

sed $line"q;d" "$TODO_FILE" | grep -o "$REGEX" | while read -r app
do
    "$TODO_FULL_SH" command append "$newest" "$app"
done
